export const VIEM_CHAIN = Symbol("VIEM_CHAIN");
export const VIEM_PUBLIC_CLIENT = Symbol("VIEM_PUBLIC_CLIENT");

export const PAYMASTER_REGISTRY = Symbol("PAYMASTER_REGISTRY");
export const SIGNER_REGISTRY = Symbol("SIGNER_REGISTRY");

export const ENTRY_POINT_REPOSITORY = Symbol("ENTRY_POINT_REPOSITORY");
export const PAYMASTER_REPOSITORY = Symbol("PAYMASTER_REPOSITORY");

export const tokenSymbols = [
  VIEM_CHAIN,
  VIEM_PUBLIC_CLIENT,
  PAYMASTER_REGISTRY,
  SIGNER_REGISTRY,
  ENTRY_POINT_REPOSITORY,
  PAYMASTER_REPOSITORY
];
