export type ApplicationErrorCode =
  // auth
  | "UNAUTHORIZED"
  | "AUTHORIZATION_INVALID"
  | "AUTHORIZATION_DELEGATE_MISMATCH"
  | "AUTHORIZATION_CHAIN_MISMATCH"

  // quote token (decode / protocol)
  | "QUOTE_TOKEN_MALFORMED"
  | "QUOTE_TOKEN_MAC_INVALID"
  | "QUOTE_TOKEN_UNSUPPORTED_VERSION"
  | "QUOTE_TOKEN_EXPIRED"
  | "QUOTE_TOKEN_CHAIN_MISMATCH"
  | "QUOTE_TOKEN_DELEGATE_MISMATCH"
  | "QUOTE_TOKEN_SPONSOR_MISMATCH"
  | "QUOTE_TOKEN_CALL_HASH_MISMATCH"
  | "QUOTE_TOKEN_NONCE_STALE"

  // validation / eligibility
  | "UNSUPPORTED_TOKEN_FOR_CHAIN"
  | "TRANSFER_AMOUNT_BELOW_MINIMUM"
  | "TOKEN_ADDRESS_UNKNOWN"

  // balance
  | "INSUFFICIENT_SEND_BALANCE"
  | "INSUFFICIENT_FEE_BALANCE"
  | "INSUFFICIENT_COMBINED_BALANCE"

  // execution / infra
  | "FAILED_TO_FETCH_NEXT_NONCE"
  | "SIMULATION_FAILED"
  | "TRANSACTION_SEND_FAILED";
