import * as v from "valibot";

import { EnvSchema } from "@/shared/validations/schemas/env.schema";

export const ENV = v.parse(EnvSchema, {
  RPC_INFURA_ID: process.env.RPC_INFURA_ID,

  SPONSOR_PK: process.env.SPONSOR_PK,
  SPONSOR_ADDRESS: process.env.SPONSOR_ADDRESS,

  QUOTE_TOKEN_SECRET: process.env.QUOTE_TOKEN_SECRET,

  THIRD_WEB_API_SECRET: process.env.THIRD_WEB_API_SECRET,

  ETH_MAIN_JPYC_TOKEN_ADDRESS: process.env.ETH_MAIN_JPYC_TOKEN_ADDRESS,
  ETH_MAIN_USDC_TOKEN_ADDRESS: process.env.ETH_MAIN_USDC_TOKEN_ADDRESS,
  ETH_MAIN_EURC_TOKEN_ADDRESS: process.env.ETH_MAIN_EURC_TOKEN_ADDRESS,

  ETH_SEPOLIA_JPYC_TOKEN_ADDRESS: process.env.ETH_SEPOLIA_JPYC_TOKEN_ADDRESS,
  ETH_SEPOLIA_USDC_TOKEN_ADDRESS: process.env.ETH_SEPOLIA_USDC_TOKEN_ADDRESS,
  ETH_SEPOLIA_EURC_TOKEN_ADDRESS: process.env.ETH_SEPOLIA_EURC_TOKEN_ADDRESS,

  ETH_MAIN_DELEGATE_ADDRESS: process.env.ETH_MAIN_DELEGATE_ADDRESS,
  ETH_MAIN_REGISTRY_ADDRESS: process.env.ETH_MAIN_REGISTRY_ADDRESS,

  ETH_SEPOLIA_DELEGATE_ADDRESS: process.env.ETH_SEPOLIA_DELEGATE_ADDRESS,
  ETH_SEPOLIA_REGISTRY_ADDRESS: process.env.ETH_SEPOLIA_REGISTRY_ADDRESS,

  ETH_JPYC_MIN_TRANSFER_AMOUNT_UNITS: process.env.ETH_JPYC_MIN_TRANSFER_AMOUNT_UNITS,
  ETH_USDC_MIN_TRANSFER_AMOUNT_UNITS: process.env.ETH_USDC_MIN_TRANSFER_AMOUNT_UNITS,
  ETH_EURC_MIN_TRANSFER_AMOUNT_UNITS: process.env.ETH_EURC_MIN_TRANSFER_AMOUNT_UNITS,

  ETH_JPYC_FIXED_FEE_AMOUNT_UNITS: process.env.ETH_JPYC_FIXED_FEE_AMOUNT_UNITS,
  ETH_USDC_FIXED_FEE_AMOUNT_UNITS: process.env.ETH_USDC_FIXED_FEE_AMOUNT_UNITS,
  ETH_EURC_FIXED_FEE_AMOUNT_UNITS: process.env.ETH_EURC_FIXED_FEE_AMOUNT_UNITS,

  BASE_MAIN_USDC_TOKEN_ADDRESS: process.env.BASE_MAIN_USDC_TOKEN_ADDRESS,
  BASE_MAIN_EURC_TOKEN_ADDRESS: process.env.BASE_MAIN_EURC_TOKEN_ADDRESS,

  BASE_SEPOLIA_USDC_TOKEN_ADDRESS: process.env.BASE_SEPOLIA_USDC_TOKEN_ADDRESS,
  BASE_SEPOLIA_EURC_TOKEN_ADDRESS: process.env.BASE_SEPOLIA_EURC_TOKEN_ADDRESS,

  BASE_MAIN_DELEGATE_ADDRESS: process.env.BASE_MAIN_DELEGATE_ADDRESS,
  BASE_MAIN_REGISTRY_ADDRESS: process.env.BASE_MAIN_REGISTRY_ADDRESS,

  BASE_SEPOLIA_DELEGATE_ADDRESS: process.env.BASE_SEPOLIA_DELEGATE_ADDRESS,
  BASE_SEPOLIA_REGISTRY_ADDRESS: process.env.BASE_SEPOLIA_REGISTRY_ADDRESS,

  BASE_USDC_MIN_TRANSFER_AMOUNT_UNITS: process.env.BASE_USDC_MIN_TRANSFER_AMOUNT_UNITS,
  BASE_EURC_MIN_TRANSFER_AMOUNT_UNITS: process.env.BASE_EURC_MIN_TRANSFER_AMOUNT_UNITS,

  BASE_USDC_FIXED_FEE_AMOUNT_UNITS: process.env.BASE_USDC_FIXED_FEE_AMOUNT_UNITS,
  BASE_EURC_FIXED_FEE_AMOUNT_UNITS: process.env.BASE_EURC_FIXED_FEE_AMOUNT_UNITS,

  POLYGON_MAIN_JPYC_TOKEN_ADDRESS: process.env.POLYGON_MAIN_JPYC_TOKEN_ADDRESS,
  POLYGON_MAIN_USDC_TOKEN_ADDRESS: process.env.POLYGON_MAIN_USDC_TOKEN_ADDRESS,

  POLYGON_AMOY_JPYC_TOKEN_ADDRESS: process.env.POLYGON_AMOY_JPYC_TOKEN_ADDRESS,
  POLYGON_AMOY_USDC_TOKEN_ADDRESS: process.env.POLYGON_AMOY_USDC_TOKEN_ADDRESS,

  POLYGON_MAIN_DELEGATE_ADDRESS: process.env.POLYGON_MAIN_DELEGATE_ADDRESS,
  POLYGON_MAIN_REGISTRY_ADDRESS: process.env.POLYGON_MAIN_REGISTRY_ADDRESS,

  POLYGON_AMOY_DELEGATE_ADDRESS: process.env.POLYGON_AMOY_DELEGATE_ADDRESS,
  POLYGON_AMOY_REGISTRY_ADDRESS: process.env.POLYGON_AMOY_REGISTRY_ADDRESS,

  POLYGON_JPYC_MIN_TRANSFER_AMOUNT_UNITS: process.env.POLYGON_JPYC_MIN_TRANSFER_AMOUNT_UNITS,
  POLYGON_USDC_MIN_TRANSFER_AMOUNT_UNITS: process.env.POLYGON_USDC_MIN_TRANSFER_AMOUNT_UNITS,

  POLYGON_JPYC_FIXED_FEE_AMOUNT_UNITS: process.env.POLYGON_JPYC_FIXED_FEE_AMOUNT_UNITS,
  POLYGON_USDC_FIXED_FEE_AMOUNT_UNITS: process.env.POLYGON_USDC_FIXED_FEE_AMOUNT_UNITS
});
