import * as v from "valibot";

import { Env, EnvSchema } from "@/shared/validations/schemas/env.schema";

export const ENV: Env = v.parse(EnvSchema, {
  NODE_ENV: process.env.NODE_ENV,

  RPC_INFURA_ID: process.env.RPC_INFURA_ID,

  SPONSOR_PK: process.env.SPONSOR_PK,
  SPONSOR_ADDRESS: process.env.SPONSOR_ADDRESS,

  QUOTE_TOKEN_SECRET: process.env.QUOTE_TOKEN_SECRET,

  MAIN_JPYC_TOKEN_ADDRESS: process.env.MAIN_JPYC_TOKEN_ADDRESS,
  MAIN_USDC_TOKEN_ADDRESS: process.env.MAIN_USDC_TOKEN_ADDRESS,
  MAIN_EURC_TOKEN_ADDRESS: process.env.MAIN_EURC_TOKEN_ADDRESS,

  MAIN_DELEGATE_ADDRESS: process.env.MAIN_DELEGATE_ADDRESS,
  MAIN_REGISTRY_ADDRESS: process.env.MAIN_REGISTRY_ADDRESS,

  MAIN_JPYC_MIN_TRANSFER_AMOUNT_UNITS: process.env.MAIN_JPYC_MIN_TRANSFER_AMOUNT_UNITS,
  MAIN_USDC_MIN_TRANSFER_AMOUNT_UNITS: process.env.MAIN_USDC_MIN_TRANSFER_AMOUNT_UNITS,
  MAIN_EURC_MIN_TRANSFER_AMOUNT_UNITS: process.env.MAIN_EURC_MIN_TRANSFER_AMOUNT_UNITS,

  MAIN_JPYC_FIXED_FEE_AMOUNT_UNITS: process.env.MAIN_JPYC_FIXED_FEE_AMOUNT_UNITS,
  MAIN_USDC_FIXED_FEE_AMOUNT_UNITS: process.env.MAIN_USDC_FIXED_FEE_AMOUNT_UNITS,
  MAIN_EURC_FIXED_FEE_AMOUNT_UNITS: process.env.MAIN_EURC_FIXED_FEE_AMOUNT_UNITS,

  BASE_USDC_TOKEN_ADDRESS: process.env.BASE_USDC_TOKEN_ADDRESS,
  BASE_EURC_TOKEN_ADDRESS: process.env.BASE_EURC_TOKEN_ADDRESS,

  BASE_DELEGATE_ADDRESS: process.env.BASE_DELEGATE_ADDRESS,
  BASE_REGISTRY_ADDRESS: process.env.BASE_REGISTRY_ADDRESS,

  BASE_USDC_MIN_TRANSFER_AMOUNT_UNITS: process.env.BASE_USDC_MIN_TRANSFER_AMOUNT_UNITS,
  BASE_EURC_MIN_TRANSFER_AMOUNT_UNITS: process.env.BASE_EURC_MIN_TRANSFER_AMOUNT_UNITS,

  BASE_USDC_FIXED_FEE_AMOUNT_UNITS: process.env.BASE_USDC_FIXED_FEE_AMOUNT_UNITS,
  BASE_EURC_FIXED_FEE_AMOUNT_UNITS: process.env.BASE_EURC_FIXED_FEE_AMOUNT_UNITS,

  POLYGON_JPYC_TOKEN_ADDRESS: process.env.POLYGON_JPYC_TOKEN_ADDRESS,
  POLYGON_USDC_TOKEN_ADDRESS: process.env.POLYGON_USDC_TOKEN_ADDRESS,

  POLYGON_DELEGATE_ADDRESS: process.env.POLYGON_DELEGATE_ADDRESS,
  POLYGON_REGISTRY_ADDRESS: process.env.POLYGON_REGISTRY_ADDRESS,

  POLYGON_JPYC_MIN_TRANSFER_AMOUNT_UNITS: process.env.POLYGON_JPYC_MIN_TRANSFER_AMOUNT_UNITS,
  POLYGON_USDC_MIN_TRANSFER_AMOUNT_UNITS: process.env.POLYGON_USDC_MIN_TRANSFER_AMOUNT_UNITS,

  POLYGON_JPYC_FIXED_FEE_AMOUNT_UNITS: process.env.POLYGON_JPYC_FIXED_FEE_AMOUNT_UNITS,
  POLYGON_USDC_FIXED_FEE_AMOUNT_UNITS: process.env.POLYGON_USDC_FIXED_FEE_AMOUNT_UNITS
});
