export const DI_TOKENS = {
  // constants
  QUOTE_TOKEN_SECRET: Symbol("QUOTE_TOKEN_SECRET"),

  // clients
  FIREBASE_CLIENT: Symbol("FIREBASE_CLIENT"),

  // policies
  APP_CHECK_POLICY: Symbol("APP_CHECK_POLICY"),
  BALANCE_SUFFICIENCY_POLICY: Symbol("BALANCE_SUFFICIENCY_POLICY"),
  CHAIN_TO_TOKEN_SUPPORT_POLICY: Symbol("CHAIN_TO_TOKEN_SUPPORT_POLICY"),
  TRANSFER_ELIGIBILITY_POLICY: Symbol("TRANSFER_ELIGIBILITY_POLICY"),

  // adapters
  APP_CHECK_ADAPTER: Symbol("APP_CHECK_ADAPTER"),
  ERC20_ADAPTER: Symbol("ERC20_ADAPTER"),
  REGISTRY_ADAPTER: Symbol("REGISTRY_ADAPTER"),
  SPONSOR_ADAPTER: Symbol("SPONSOR_ADAPTER"),

  // gateways
  MORALIS_GATEWAY: Symbol("MORALIS_GATEWAY"),

  // repositories
  TOKEN_DEPLOYMENT_REPOSITORY: Symbol("TOKEN_DEPLOYMENT_REPOSITORY")
} as const;
