import * as v from "valibot";

import { Env, EnvSchema } from "../validations/schemas/env.schema";

export const ENV: Env = v.parse(EnvSchema, {
  NODE_ENV: process.env.NODE_ENV,

  RPC_INFURA_ID: process.env.RPC_INFURA_ID,

  SPONSOR_ADDRESS: process.env.SPONSOR_ADDRESS,
  SPONSOR_PK: process.env.SPONSOR_PK,

  QUOTE_TOKEN_SECRET: process.env.QUOTE_TOKEN_SECRET,

  JPYC_TOKEN_ADDRESS: process.env.JPYC_TOKEN_ADDRESS,
  USDC_TOKEN_ADDRESS: process.env.USDC_TOKEN_ADDRESS,
  EURC_TOKEN_ADDRESS: process.env.EURC_TOKEN_ADDRESS,

  MAIN_DELEGATE_ADDRESS: process.env.MAIN_DELEGATE_ADDRESS,
  MAIN_REGISTRY_ADDRESS: process.env.MAIN_REGISTRY_ADDRESS,

  MAIN_FEE_BPS: process.env.MAIN_FEE_BPS,
  MAIN_JPYC_FEE_CAP_UNITS: process.env.MAIN_JPYC_FEE_CAP_UNITS,
  MAIN_USDC_FEE_CAP_UNITS: process.env.MAIN_USDC_FEE_CAP_UNITS,
  MAIN_EURC_FEE_CAP_UNITS: process.env.MAIN_EURC_FEE_CAP_UNITS,

  BASE_DELEGATE_ADDRESS: process.env.BASE_DELEGATE_ADDRESS,
  BASE_REGISTRY_ADDRESS: process.env.BASE_REGISTRY_ADDRESS,

  BASE_FEE_BPS: process.env.BASE_FEE_BPS,
  BASE_JPYC_FEE_CAP_UNITS: process.env.BASE_JPYC_FEE_CAP_UNITS,
  BASE_USDC_FEE_CAP_UNITS: process.env.BASE_USDC_FEE_CAP_UNITS,
  BASE_EURC_FEE_CAP_UNITS: process.env.BASE_EURC_FEE_CAP_UNITS
});
