import * as v from "valibot";

import { hex32Validator, addressValidator, hex64Validator } from "../rules/address.validator";
import { stringBigintValidator } from "../rules/string-bigint.validator";

export const EnvSchema = v.object({
  NODE_ENV: v.union([v.literal("dev"), v.literal("prd")]),

  RPC_INFURA_ID: hex32Validator("RPC_INFURA_ID"),

  SPONSOR_PK: hex64Validator("SPONSOR_PK"),
  SPONSOR_ADDRESS: addressValidator("SPONSOR_ADDRESS"),

  QUOTE_TOKEN_SECRET: hex64Validator("QUOTE_TOKEN_SECRET"),

  MAIN_JPYC_TOKEN_ADDRESS: addressValidator("MAIN_JPYC_TOKEN_ADDRESS"),
  MAIN_USDC_TOKEN_ADDRESS: addressValidator("MAIN_USDC_TOKEN_ADDRESS"),
  MAIN_EURC_TOKEN_ADDRESS: addressValidator("MAIN_EURC_TOKEN_ADDRESS"),

  MAIN_DELEGATE_ADDRESS: addressValidator("MAIN_DELEGATE_ADDRESS"),
  MAIN_REGISTRY_ADDRESS: addressValidator("MAIN_REGISTRY_ADDRESS"),

  MAIN_JPYC_MIN_TRANSFER_AMOUNT_UNITS: stringBigintValidator("MAIN_JPYC_MIN_TRANSFER_AMOUNT_UNITS"),
  MAIN_USDC_MIN_TRANSFER_AMOUNT_UNITS: stringBigintValidator("MAIN_USDC_MIN_TRANSFER_AMOUNT_UNITS"),
  MAIN_EURC_MIN_TRANSFER_AMOUNT_UNITS: stringBigintValidator("MAIN_EURC_MIN_TRANSFER_AMOUNT_UNITS"),

  MAIN_JPYC_FIXED_FEE_AMOUNT_UNITS: stringBigintValidator("MAIN_JPYC_FIXED_FEE_AMOUNT_UNITS"),
  MAIN_USDC_FIXED_FEE_AMOUNT_UNITS: stringBigintValidator("MAIN_USDC_FIXED_FEE_AMOUNT_UNITS"),
  MAIN_EURC_FIXED_FEE_AMOUNT_UNITS: stringBigintValidator("MAIN_EURC_FIXED_FEE_AMOUNT_UNITS"),

  BASE_USDC_TOKEN_ADDRESS: addressValidator("BASE_USDC_TOKEN_ADDRESS"),
  BASE_EURC_TOKEN_ADDRESS: addressValidator("BASE_EURC_TOKEN_ADDRESS"),

  BASE_DELEGATE_ADDRESS: addressValidator("BASE_DELEGATE_ADDRESS"),
  BASE_REGISTRY_ADDRESS: addressValidator("BASE_REGISTRY_ADDRESS"),

  BASE_USDC_MIN_TRANSFER_AMOUNT_UNITS: stringBigintValidator("BASE_USDC_MIN_TRANSFER_AMOUNT_UNITS"),
  BASE_EURC_MIN_TRANSFER_AMOUNT_UNITS: stringBigintValidator("BASE_EURC_MIN_TRANSFER_AMOUNT_UNITS"),

  BASE_USDC_FIXED_FEE_AMOUNT_UNITS: stringBigintValidator("BASE_USDC_FIXED_FEE_AMOUNT_UNITS"),
  BASE_EURC_FIXED_FEE_AMOUNT_UNITS: stringBigintValidator("BASE_EURC_FIXED_FEE_AMOUNT_UNITS"),

  POLYGON_JPYC_TOKEN_ADDRESS: addressValidator("POLYGON_JPYC_TOKEN_ADDRESS"),
  POLYGON_USDC_TOKEN_ADDRESS: addressValidator("POLYGON_USDC_TOKEN_ADDRESS"),

  POLYGON_DELEGATE_ADDRESS: addressValidator("POLYGON_DELEGATE_ADDRESS"),
  POLYGON_REGISTRY_ADDRESS: addressValidator("POLYGON_REGISTRY_ADDRESS"),

  POLYGON_JPYC_MIN_TRANSFER_AMOUNT_UNITS: stringBigintValidator("POLYGON_JPYC_MIN_TRANSFER_AMOUNT_UNITS"),
  POLYGON_USDC_MIN_TRANSFER_AMOUNT_UNITS: stringBigintValidator("POLYGON_USDC_MIN_TRANSFER_AMOUNT_UNITS"),

  POLYGON_JPYC_FIXED_FEE_AMOUNT_UNITS: stringBigintValidator("POLYGON_JPYC_FIXED_FEE_AMOUNT_UNITS"),
  POLYGON_USDC_FIXED_FEE_AMOUNT_UNITS: stringBigintValidator("POLYGON_USDC_FIXED_FEE_AMOUNT_UNITS")
});
export type Env = v.InferOutput<typeof EnvSchema>;
