import * as v from "valibot";

import { hex32Validator, addressValidator, hex64Validator } from "../rules/address.validator";
import { stringBigintValidator } from "../rules/string-bigint.validator";

export const EnvSchema = v.object({
  RPC_INFURA_ID: hex32Validator("RPC_INFURA_ID"),

  SPONSOR_PK: hex64Validator("SPONSOR_PK"),
  SPONSOR_ADDRESS: addressValidator("SPONSOR_ADDRESS"),

  QUOTE_TOKEN_SECRET: hex64Validator("QUOTE_TOKEN_SECRET"),

  THIRD_WEB_API_SECRET: v.string("THIRD_WEB_API_SECRET must be a string."),
  MORARIS_API_SECRET: v.string("MORARIS_API_SECRET must be a string."),

  ETH_MAIN_JPYC_TOKEN_ADDRESS: addressValidator("ETH_MAIN_JPYC_TOKEN_ADDRESS"),
  ETH_MAIN_USDC_TOKEN_ADDRESS: addressValidator("ETH_MAIN_USDC_TOKEN_ADDRESS"),
  ETH_MAIN_EURC_TOKEN_ADDRESS: addressValidator("ETH_MAIN_EURC_TOKEN_ADDRESS"),

  ETH_SEPOLIA_JPYC_TOKEN_ADDRESS: addressValidator("ETH_SEPOLIA_JPYC_TOKEN_ADDRESS"),
  ETH_SEPOLIA_USDC_TOKEN_ADDRESS: addressValidator("ETH_SEPOLIA_USDC_TOKEN_ADDRESS"),
  ETH_SEPOLIA_EURC_TOKEN_ADDRESS: addressValidator("ETH_SEPOLIA_EURC_TOKEN_ADDRESS"),

  ETH_MAIN_DELEGATE_ADDRESS: addressValidator("ETH_MAIN_DELEGATE_ADDRESS"),
  ETH_MAIN_REGISTRY_ADDRESS: addressValidator("ETH_MAIN_REGISTRY_ADDRESS"),

  ETH_SEPOLIA_DELEGATE_ADDRESS: addressValidator("ETH_SEPOLIA_DELEGATE_ADDRESS"),
  ETH_SEPOLIA_REGISTRY_ADDRESS: addressValidator("ETH_SEPOLIA_REGISTRY_ADDRESS"),

  ETH_JPYC_MIN_TRANSFER_AMOUNT_UNITS: stringBigintValidator("ETH_JPYC_MIN_TRANSFER_AMOUNT_UNITS"),
  ETH_USDC_MIN_TRANSFER_AMOUNT_UNITS: stringBigintValidator("ETH_USDC_MIN_TRANSFER_AMOUNT_UNITS"),
  ETH_EURC_MIN_TRANSFER_AMOUNT_UNITS: stringBigintValidator("ETH_EURC_MIN_TRANSFER_AMOUNT_UNITS"),

  ETH_JPYC_FIXED_FEE_AMOUNT_UNITS: stringBigintValidator("ETH_JPYC_FIXED_FEE_AMOUNT_UNITS"),
  ETH_USDC_FIXED_FEE_AMOUNT_UNITS: stringBigintValidator("ETH_USDC_FIXED_FEE_AMOUNT_UNITS"),
  ETH_EURC_FIXED_FEE_AMOUNT_UNITS: stringBigintValidator("ETH_EURC_FIXED_FEE_AMOUNT_UNITS"),

  BASE_MAIN_USDC_TOKEN_ADDRESS: addressValidator("BASE_MAIN_USDC_TOKEN_ADDRESS"),
  BASE_MAIN_EURC_TOKEN_ADDRESS: addressValidator("BASE_MAIN_EURC_TOKEN_ADDRESS"),

  BASE_SEPOLIA_USDC_TOKEN_ADDRESS: addressValidator("BASE_SEPOLIA_USDC_TOKEN_ADDRESS"),
  BASE_SEPOLIA_EURC_TOKEN_ADDRESS: addressValidator("BASE_SEPOLIA_EURC_TOKEN_ADDRESS"),

  BASE_MAIN_DELEGATE_ADDRESS: addressValidator("BASE_MAIN_DELEGATE_ADDRESS"),
  BASE_MAIN_REGISTRY_ADDRESS: addressValidator("BASE_MAIN_REGISTRY_ADDRESS"),

  BASE_SEPOLIA_DELEGATE_ADDRESS: addressValidator("BASE_SEPOLIA_DELEGATE_ADDRESS"),
  BASE_SEPOLIA_REGISTRY_ADDRESS: addressValidator("BASE_SEPOLIA_REGISTRY_ADDRESS"),

  BASE_USDC_MIN_TRANSFER_AMOUNT_UNITS: stringBigintValidator("BASE_USDC_MIN_TRANSFER_AMOUNT_UNITS"),
  BASE_EURC_MIN_TRANSFER_AMOUNT_UNITS: stringBigintValidator("BASE_EURC_MIN_TRANSFER_AMOUNT_UNITS"),

  BASE_USDC_FIXED_FEE_AMOUNT_UNITS: stringBigintValidator("BASE_USDC_FIXED_FEE_AMOUNT_UNITS"),
  BASE_EURC_FIXED_FEE_AMOUNT_UNITS: stringBigintValidator("BASE_EURC_FIXED_FEE_AMOUNT_UNITS"),

  POLYGON_MAIN_JPYC_TOKEN_ADDRESS: addressValidator("POLYGON_MAIN_JPYC_TOKEN_ADDRESS"),
  POLYGON_MAIN_USDC_TOKEN_ADDRESS: addressValidator("POLYGON_MAIN_USDC_TOKEN_ADDRESS"),

  POLYGON_AMOY_JPYC_TOKEN_ADDRESS: addressValidator("POLYGON_AMOY_JPYC_TOKEN_ADDRESS"),
  POLYGON_AMOY_USDC_TOKEN_ADDRESS: addressValidator("POLYGON_AMOY_USDC_TOKEN_ADDRESS"),

  POLYGON_MAIN_DELEGATE_ADDRESS: addressValidator("POLYGON_MAIN_DELEGATE_ADDRESS"),
  POLYGON_MAIN_REGISTRY_ADDRESS: addressValidator("POLYGON_MAIN_REGISTRY_ADDRESS"),

  POLYGON_AMOY_DELEGATE_ADDRESS: addressValidator("POLYGON_AMOY_DELEGATE_ADDRESS"),
  POLYGON_AMOY_REGISTRY_ADDRESS: addressValidator("POLYGON_AMOY_REGISTRY_ADDRESS"),

  POLYGON_JPYC_MIN_TRANSFER_AMOUNT_UNITS: stringBigintValidator("POLYGON_JPYC_MIN_TRANSFER_AMOUNT_UNITS"),
  POLYGON_USDC_MIN_TRANSFER_AMOUNT_UNITS: stringBigintValidator("POLYGON_USDC_MIN_TRANSFER_AMOUNT_UNITS"),

  POLYGON_JPYC_FIXED_FEE_AMOUNT_UNITS: stringBigintValidator("POLYGON_JPYC_FIXED_FEE_AMOUNT_UNITS"),
  POLYGON_USDC_FIXED_FEE_AMOUNT_UNITS: stringBigintValidator("POLYGON_USDC_FIXED_FEE_AMOUNT_UNITS")
});
