name: Do test on develop merge

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: yarn

      - run: yarn install --immutable

      - name: Run tests
        run: yarn test:ci:cov
        env:
          RPC_INFURA_ID: "02834402f4c542519e41a81e2e7bba66"
          QUOTE_TOKEN_SECRET: ${{ secrets.QUOTE_TOKEN_SECRET }}
          SPONSOR_PK: ${{ secrets.SPONSOR_PK }}
          SPONSOR_ADDRESS: "0xf0BF1971B04787fC0dE4f8Ad40d00EAC2562f9A8"
          MORALIS_API_SECRET: ${{ secrets.MORALIS_API_SECRET }}
          FIREBASE_ADMIN_SECRET: ${{ secrets.FIREBASE_ADMIN_SECRET }}
          ETH_JPYC_FIXED_FEE_AMOUNT_UNITS: "100000000000000000000"
          ETH_JPYC_MIN_TRANSFER_AMOUNT_UNITS: "1000000000000000000000"
          ETH_USDC_FIXED_FEE_AMOUNT_UNITS: "1000000"
          ETH_USDC_MIN_TRANSFER_AMOUNT_UNITS: "10000000"
          ETH_EURC_FIXED_FEE_AMOUNT_UNITS: "1000000"
          ETH_EURC_MIN_TRANSFER_AMOUNT_UNITS: "10000000"
          ETH_MAIN_DELEGATE_ADDRESS: "0xeD269D025dCed3a7d192923BFaaf605ef830e338"
          ETH_MAIN_REGISTRY_ADDRESS: "0xb631172683DA82B2C87D8f84E2C51698D0719e8C"
          ETH_SEPOLIA_DELEGATE_ADDRESS: "0xA9Ea67F7A3990d40745Dfb46D61e3A416a8018a2"
          ETH_SEPOLIA_REGISTRY_ADDRESS: "0xeD269D025dCed3a7d192923BFaaf605ef830e338"
          BASE_USDC_FIXED_FEE_AMOUNT_UNITS: "50000"
          BASE_USDC_MIN_TRANSFER_AMOUNT_UNITS: "3000000"
          BASE_EURC_FIXED_FEE_AMOUNT_UNITS: "50000"
          BASE_EURC_MIN_TRANSFER_AMOUNT_UNITS: "3000000"
          BASE_MAIN_DELEGATE_ADDRESS: "0xb820D66Ba5501232a3CF4a00FdF9e3f0e5eCE85C"
          BASE_MAIN_REGISTRY_ADDRESS: "0xaf264eaB8D01A54F064Ee17951aA6b6f3836DC26"
          BASE_SEPOLIA_DELEGATE_ADDRESS: "0xe6D0F40a9933C176b3BE5D9830D8E564400c8231"
          BASE_SEPOLIA_REGISTRY_ADDRESS: "0x2493548c692c3Ff919000A6e788Cc0E2047d11E0"
          POLYGON_JPYC_FIXED_FEE_AMOUNT_UNITS: "2000000000000000000"
          POLYGON_JPYC_MIN_TRANSFER_AMOUNT_UNITS: "100000000000000000000"
          POLYGON_USDC_FIXED_FEE_AMOUNT_UNITS: "20000"
          POLYGON_USDC_MIN_TRANSFER_AMOUNT_UNITS: "2000000"
          POLYGON_MAIN_DELEGATE_ADDRESS: "0xeD269D025dCed3a7d192923BFaaf605ef830e338"
          POLYGON_MAIN_REGISTRY_ADDRESS: "0xb631172683DA82B2C87D8f84E2C51698D0719e8C"
          POLYGON_AMOY_DELEGATE_ADDRESS: "0x3f80037AeC2DFfd88a193c58161bB1CDcA1ecF6a"
          POLYGON_AMOY_REGISTRY_ADDRESS: "0x773c5cA412751a5a2cD24e4d706bb417AFF2F531"

      - name: Upload coverage report
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: coverage-report
          path: coverage/
          retention-days: 14
